^C


In [1]:
import numpy as np
import pickle

import tensorflow as tf
from tensorflow.keras import models, layers

In [2]:
import sys

print("--sys.version—")
print(sys.version)

--sys.version—
3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]


In [18]:
dataset_pre = np.load("dataset_pre.npy")
dataset_test_pre = np.load("dataset_test_pre.npy")
dataset_pre_labels = np.load("dataset_pre_labels.npy")
dataset_test_pre_labels = np.load("dataset_test_pre_labels.npy")

In [6]:
print(dataset_pre.shape)
print(dataset_test_pre.shape)
print(dataset_pre_labels.shape)
print(dataset_test_pre_labels.shape)

(46000, 16, 256, 3)
(4600, 16, 256, 3)
(46000,)
(4600,)


In [7]:
dataset_pre_labels[45990:46000]

array([23, 23, 23, 23, 23, 23, 23, 23, 23, 23])

In [74]:
n_labels = len(np.unique(dataset_pre_labels))
np.unique(dataset_pre_labels)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [3]:
with open('table_.pkl','rb') as f:
    tabel = pickle.load(f)

In [4]:
tabel.items()

dict_items([('book', 1), ('book-holder', 2), ('coffee-machine', 3), ('laptop', 4), ('mirror', 5), ('tissue-box', 6), ('monitor', 7), ('pot', 8), ('router', 9), ('purse(hand)', 10), ('hair-dryer(hand)', 11), ('spray(hand)', 12), ('water-bottle(hand)', 13), ('medicine-bottle(hand)', 14), ('glass-jar(hand)', 15), ('paper-cup(hand)', 16), ('tumbler(hand)', 17), ('tablet-pc(hand)', 18), ('smartwatch(wrist)', 19), ('bicycle', 20), ('fire-extinguisher', 21), ('stool', 22), ('guitar(knee)', 23)])

In [23]:
train_labels = np.zeros((dataset_pre_labels.shape[0], 23))
test_labels = np.zeros((dataset_test_pre_labels.shape[0], 23))
for i, n in enumerate(dataset_pre_labels):
    train_labels[n] = 1
for i, n in enumerate(dataset_test_pre_labels):
    test_labels[n] = 1

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer


mlb = MultiLabelBinarizer()

train_labels = mlb.fit_transform(np.array(dataset_pre_labels, dtype='str'))
test_labels = mlb.fit_transform(np.array(dataset_test_pre_labels, dtype='str'))

In [17]:
print(len(np.unique(train_labels, axis=0)))
for i in np.unique(train_labels, axis=0):
    print(i)

23
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0]
[0 0 1 0 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 1 0]
[0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0]
[0 0 1 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 0 0 0 0 0]
[0 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0]
[1 1 0 1 0 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0]
[1 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1]
[1 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0]
[1 1 0 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 0]
[1 1 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0 0]
[1 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 1 0 0 1 1 0 0 0 0 0]
[1 1 1 1 0 0 1 1 0 0 1 1 

In [83]:
input_shape=(16,256,3)
CNNmodel = models.Sequential()
CNNmodel.add(layers.Conv2D(64, (3, 3), activation='relu', input_shape=input_shape))
CNNmodel.add(layers.MaxPooling2D((2, 2)))
CNNmodel.add(layers.Dropout(0.2))
"""
CNNmodel.add(layers.Conv2D(64, (3, 3), activation='relu'))
CNNmodel.add(layers.MaxPooling2D((2, 2)))
CNNmodel.add(layers.Dropout(0.2))
CNNmodel.add(layers.Conv2D(64, (3, 3), activation='relu'))
"""
CNNmodel.add(layers.Flatten())
CNNmodel.add(layers.Dense(64, activation='relu'))
CNNmodel.add(layers.Dropout(0.2))
CNNmodel.add(layers.Dense(32, activation='relu'))
CNNmodel.add(layers.Dense(len(train_labels[0]), activation='softmax'))

In [84]:

from tensorflow.keras import optimizers
adam = optimizers.Adam(lr = 0.001)
CNNmodel.summary()
CNNmodel.compile(loss = 'categorical_crossentropy', optimizer = adam, metrics = ['accuracy'])

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 14, 254, 64)       1792      
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 7, 127, 64)        0         
_________________________________________________________________
dropout_14 (Dropout)         (None, 7, 127, 64)        0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 56896)             0         
_________________________________________________________________
dense_18 (Dense)             (None, 64)                3641408   
_________________________________________________________________
dropout_15 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_19 (Dense)             (None, 32)               

In [ ]:
history = CNNmodel.fit(dataset_pre, train_labels, batch_size = 100, validation_split = 0.2, epochs = 100, verbose = 1)

Epoch 1/100
368/368 [==============================] - 81s 221ms/step - loss: 18820057088.0000 - accuracy: 0.1014 - val_loss: 65277038592.0000 - val_accuracy: 0.0000e+00
Epoch 2/100
368/368 [==============================] - 80s 217ms/step - loss: 258424274944.0000 - accuracy: 0.0898 - val_loss: 458260348928.0000 - val_accuracy: 0.0000e+00
Epoch 3/100
368/368 [==============================] - 97s 264ms/step - loss: 1054872240128.0000 - accuracy: 0.0745 - val_loss: 1555170721792.0000 - val_accuracy: 0.0000e+00
Epoch 4/100
285/368 [======================>.......] - ETA: 43s - loss: 2588158459904.0000 - accuracy: 0.0659

In [97]:
from sklearn.metrics import accuracy_score
y_pred = clf.predict(dataset_test_pre)

accuracy_score(test_labels, y_pred)

0.9360869565217391